GET http://localhost:8000/activity/

###

GET http://localhost:8000/activity/62ec768bdfc9c2512739ece8

###

POST http://localhost:8000/activity
Content-Type: application/json

        {
    "message": "Complete TodoApp on Frontend Mentor",
    "completed": false,
    "isDeleatable": false
        }



###
PATCH http://localhost:8000/activity/62ec768bdfc9c2512739ece8
Content-Type: application/json

{
    "completed": true
}

###
DELETE http://localhost:8000/activity/62ed6a85a4ccdab716734fc4
