GET http://localhost:8000/activity

###

GET http://localhost:8000/activity/62ec768bdfc9c2512739ece8

###

POST http://localhost:8000/activity
Content-Type: application/json

        {
            "message": "Complete Todo App on Frontend Mentor",
            "completed": false
        }



###
PATCH http://localhost:8000/activity/62ec768bdfc9c2512739ece8
Content-Type: application/json

{
    "completed": true
}

###
DELETE http://localhost:8000/activity/62ec768bdfc9c2512739ece8
